branch-defaults:
  default:
    environment: valhalla-app-dev
  parent-menu:
    environment: valhalla-app-dev
environment-defaults:
  valhalla-app-dev:
    branch: null
    repository: null
global:
  application_name: valhalla-app
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:us-west-1::platform/Python 3.4 running
    on 64bit Amazon Linux/2.4.2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
