# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('drill_id', models.CharField(blank=True, default=uuid.uuid4, max_length=500, primary_key=True, serialize=False, unique=True)),
                ('risk', models.CharField(blank=True, default=1, max_length=500)),
                ('reason', models.CharField(blank=True, default=1, max_length=500)),
                ('workstation_count_estimate', models.CharField(blank=True, max_length=500)),
                ('has_report', models.CharField(blank=True, choices=[('1', "I have a report, let's continue."), ('2', "I don't have a report like this.")], default='1', max_length=500)),
                ('workstation_count_active', models.CharField(blank=True, max_length=500)),
                ('workstation_count_auth', models.CharField(blank=True, max_length=500)),
                ('active_percent', models.CharField(blank=True, max_length=500)),
                ('auth_percent', models.CharField(blank=True, max_length=500)),
                ('wannacry_count', models.CharField(blank=True, max_length=500)),
                ('doublepulsar_count', models.CharField(blank=True, max_length=500)),
                ('heartbleed_count', models.CharField(blank=True, max_length=500)),
                ('shellshock_count', models.CharField(blank=True, max_length=500)),
                ('mirai_count', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
