# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('drill_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, choices=[('1', 'IT Manager'), ('2', 'Executive'), ('3', 'Other')], max_length=100)),
                ('workstation_count_estimate', models.CharField(blank=True, max_length=10)),
                ('has_report', models.CharField(blank=True, choices=[('1', "I have a report, let's continue."), ('2', "I don't have a report like this.")], default='1', max_length=10)),
                ('workstation_count_active', models.CharField(blank=True, max_length=10)),
                ('workstation_count_auth', models.CharField(blank=True, max_length=10)),
                ('active_percent', models.CharField(blank=True, max_length=10)),
                ('auth_percent', models.CharField(blank=True, max_length=10)),
                ('risk', models.CharField(blank=True, default=1, max_length=100)),
                ('reason', models.CharField(blank=True, default=1, max_length=300)),
            ],
        ),
    ]
