# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='has_network_monitoring',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='drill',
            name='wannacry_notification_time',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
