# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='has_report',
            field=models.CharField(blank=True, choices=[('1', "I have a report, let's continue."), ('2', "I don't have a report like this.")], default='1', max_length=100),
        ),
    ]
