# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170821_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='has_network_monitoring',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=500),
        ),
    ]
