# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170807_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='active_percent',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='drill',
            name='auth_percent',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='drill',
            name='drill_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=500, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='drill',
            name='has_report',
            field=models.CharField(blank=True, choices=[('1', "I have a report, let's continue."), ('2', "I don't have a report like this.")], default='1', max_length=500),
        ),
        migrations.AlterField(
            model_name='drill',
            name='reason',
            field=models.CharField(blank=True, default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='drill',
            name='risk',
            field=models.CharField(blank=True, default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='drill',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'IT Manager'), ('2', 'Executive'), ('3', 'Other')], max_length=500),
        ),
        migrations.AlterField(
            model_name='drill',
            name='workstation_count_active',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='drill',
            name='workstation_count_auth',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='drill',
            name='workstation_count_estimate',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
