# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170807_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drill',
            name='email',
        ),
        migrations.RemoveField(
            model_name='drill',
            name='role',
        ),
        migrations.AddField(
            model_name='drill',
            name='doublepulsar_count',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='drill',
            name='heartbleed_count',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='drill',
            name='mirai_count',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='drill',
            name='shellshock_count',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='drill',
            name='wannacry_count',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
