# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170828_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='independent_scan',
            field=models.CharField(blank=True, choices=[('1', "We'll run the scans."), ('2', 'A third-party will run the scans.')], default='1', max_length=500),
        ),
    ]
