# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_drill_independent_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='has_auth',
            field=models.CharField(blank=True, choices=[('1', 'Confirmed successful authentication.'), ('2', 'No successful authentication.')], default='1', max_length=500),
        ),
        migrations.AlterField(
            model_name='drill',
            name='has_eternalblue',
            field=models.CharField(blank=True, choices=[('1', 'Eternal Blue vulnerability detected.'), ('2', 'No cases of Eternal Blue.')], default='1', max_length=500),
        ),
    ]
