# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20170902_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='has_auth',
            field=models.CharField(blank=True, choices=[('1', 'Confirmed successful authentication'), ('2', 'No successful authentication')], default='1', max_length=500),
        ),
        migrations.AlterField(
            model_name='drill',
            name='has_eternalblue',
            field=models.CharField(blank=True, choices=[('1', 'Found Eternal Blue vulnerability'), ('2', 'No cases of Eternal Blue found')], default='1', max_length=500),
        ),
        migrations.AlterField(
            model_name='drill',
            name='has_report',
            field=models.CharField(blank=True, choices=[('1', 'I have a vulnerability scan report'), ('2', "I don't have a report like this")], default='1', max_length=500),
        ),
        migrations.AlterField(
            model_name='drill',
            name='independent_scan',
            field=models.CharField(blank=True, choices=[('1', "We'll run the scans ourselves"), ('2', 'A third-party will run the scans')], default='1', max_length=500),
        ),
    ]
